BEGIN;

CREATE TABLE IF NOT EXISTS catalog_groups (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_type varchar(20) NOT NULL CHECK (group_type IN ('sector', 'collection')),
  name varchar(200) NOT NULL,
  slug varchar(200) NOT NULL,
  display_order integer DEFAULT 0,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (group_type, slug)
);

CREATE TABLE IF NOT EXISTS product_catalog_groups (
  product_id integer NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  catalog_group_id integer NOT NULL REFERENCES catalog_groups(id) ON DELETE CASCADE,
  source varchar(50) NOT NULL DEFAULT 'ralawise-categorisation',
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (product_id, catalog_group_id)
);

CREATE INDEX IF NOT EXISTS idx_product_catalog_groups_group
  ON product_catalog_groups (catalog_group_id, product_id);

CREATE TABLE IF NOT EXISTS catalog_group_import_state (
  id smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  source_hash varchar(64) NOT NULL,
  applied_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

COMMIT;
